### ISSUE TITLE
Import PixelBoard WebSocket code

### ISSUE THREAD

**Issue by modeco80** [computernewb/collab-vm-server#100]
besides being issue #100, this will result in slightly cleaner websocket code (least I think so) and may possibly lead me further onto starting fresh? idk though.

also WebSocket-- kinda WebSocket Sucks and was written basically just to work.

**Comment by yellows111** [comment]
> also WebSocket-- kinda WebSocket Sucks and was written basically just to work.

&lt;irrelevant&gt;Wouldn't that be WebSucket or what?&lt;/irrelevant&gt;

Other than that, this sounds interesting if it works as we'd want to.

**Comment by modeco80** [comment]
well I finally finished it so i can hopefully extract the tree (it should be pretty jaja ez considering i intentionally made this code pretty generic, its basically only pixelboard in name)
