### ISSUE TITLE
Server crashes on startup

### ISSUE THREAD

**Issue by qtAmyVT** [computernewb/collab-vm-server#110]
OS: `Debian 11`
Release: `master/1.2.11`
Boost Version: `1.70.0`

Console Log:
```
Collab VM Server started
Illegal instruction
```

**Comment by modeco80** [comment]
I'm assuming some of the binaries are compiled with `-march=native -mtune=native`

On the ryzen host (if dartz used the server to compile) that means compiler probably autovectorized stuff to use sse4/avx/avx2/avx256. whoops

**Comment by qtAmyVT** [comment]
If i'm right it was precompiled (https://github.com/computernewb/collab-vm-server/releases/tag/1.2.11).

**Comment by modeco80** [comment]
Yeah the ryzen box would have been used to compile those.

**Comment by qtAmyVT** [comment]
The debian version is already broken on default?

**Comment by modeco80** [comment]
Just build the server.

Closing
