### ISSUE TITLE
Chat-linking issue (1.2.11)

### ISSUE THREAD

**Issue by DESKTOPGOOOSE** [computernewb/collab-vm-server#114]
Whenever joining a VM, the chats seem to be linked. For example, I host a Windows 10 and Vista UserVM. The people on the Windows 10 VM see the messages people are sending on the Vista VM. This seems to not be happening on 1.2.10 and I have only found this issue on 1.2.11, Could this be a misconfiguration on my end or a bug in the server?

OS: Ubuntu 21.10 x86_64
Server: 1.2.11 (Built manually with JPEG)
![chatlinking](https://user-images.githubusercontent.com/77574002/147881914-97e941c5-4267-4606-afec-f13aaad17a77.PNG)

**Comment by ghost** [comment]
This is a known bug, for the time being, run a separate instance of `collab-vm-server` for each VM.

**Comment by yellows111** [comment]
This is a known issue, and the way we fix it is by hosting only 1 VM per server process.

**Comment by dartzcn** [comment]
1.2.11 is not really being worked on except for really bad security fixes at this point. This will be fixed in CVM 3.0.
