### ISSUE TITLE
Check if the plugin directory exists

### ISSUE THREAD

**Issue by itsvic-dev** [computernewb/collab-vm-server#116]
In the current implementation of the plugin manager, it doesn't care to see if the plugins directory exists:

```cpp
bool PluginManager::Init() {
	// resize to a sane size
	g_PluginSos.resize(5);

	for(auto& it : std::filesystem::directory_iterator(std::filesystem::current_path() / "plugins")) {
		spdlog::info("Going to load plugin {}", it.path().string());
		if(!this->LoadPlugin(it.path())) {
			spdlog::warn("Plugin {} failed to load :(", it.path().string());
		}
	}

	// FIXME: would there ever be a fatal case?
	return true;
}
```

Which in turn causes the following error:
```cpp
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: directory iterator cannot open directory: No such file or directory [/home/omame/Documents/cvm-server-3/build/plugins]
[1]    86859 abort (core dumped)  
```

You could use [`std::filesystem::exists`](https://en.cppreference.com/w/cpp/filesystem/exists) to check if the directory exists, then return out of `PluginManager::Init` with `false` (and probably log an error before the return).

**Comment by dartzcn** [comment]
Fixed in https://github.com/computernewb/collab-vm-server/commit/3e270c17d6a371b1bd3137004a1113baecc3e19a

Closed.
