### ISSUE TITLE
Server has the chance to crash with a segfault when stopping a VM and starting it again.

### ISSUE THREAD

**Issue by DESKTOPGOOOSE** [computernewb/collab-vm-server#121]
Host: Ubuntu 20.04.3 LTS
CollabVM Server version: 1.2.11 (built with JPEG, not a prebuilt binary)

Starting and stopping a VM has the chance to get the server to segfault and crash, This didn't happen with 1.2.10 and it's new for me in 1.2.11. 
Before the server crashed, there was this mess of crash report and QEMU log.
![crash](https://user-images.githubusercontent.com/77574002/152405802-058d001e-4e38-4b73-a482-b7dbcde48e70.PNG)

**Comment by yellows111** [comment]
build debug and run in gdb and try to repro

**Comment by DESKTOPGOOOSE** [comment]
Output from gdb
![gdbresult](https://user-images.githubusercontent.com/77574002/152414483-86fb6a22-e158-4bd2-986d-805b1563a9f6.png)

**Comment by yellows111** [comment]
thumbnail generation crashing again? that's annoying.

feel free to save and upload the `thread apply all bt` output for analysis.

**Comment by DESKTOPGOOOSE** [comment]
![gdbthread](https://user-images.githubusercontent.com/77574002/152416992-c5d6d8dd-b16e-4b48-94bc-d5681fddf9bc.PNG)
if i did that right

**Comment by SyscoreV1** [comment]
Not random chance of crashing, 

1. Start vm
2. stop vm
3. Change a line in qemucmd
4. Start vm
5. Crash
6. 
tested with 1.2.11 main

**Comment by dakrk** [comment]
where'd 6 go

**Comment by Undefishin** [comment]
6. ???
7. PROFIT

**Comment by SyscoreV1** [comment]
6. Its a feature
7. 

nano add
#!/bin/sh
while true; do
./collabvmserver 6004
sleep 1
Echo restarting...
sleep 2
done;



Chmod +x add
./add

**Comment by mvoolt** [comment]
> 6. Its a feature
> 
> nano add #!/bin/sh while true; do ./collabvmserver 6004 sleep 1 Echo restarting... sleep 2 done;
> 
> Chmod +x add ./add

Have you learned the existence of init systems and services, Trycs? I hope you did because making a service is better than what you have done.

**Comment by SyscoreV1** [comment]
Imagine using a service, 

use another script to start screen & all 12 cvm is way faster. With docker its trash.

**Comment by dakrk** [comment]
fucking why
writing the services properly is much better than _that_

**Comment by modeco80** [comment]
> Imagine using a service,
> 
> use another script to start screen & all 12 cvm is way faster. With docker its trash.

Yeah, who needs:
 - proper system logging, proper logging rotation
 - auto-restart which is not script based, and intelligent
 - on-stop commands
 - ability to control a group of services
 - cgroups-based containment of all (child) processes so that a restart kills all residual processes and sets up a clean environment
 
That's just hipster shit.

/s (if you're too stupid to tell)

**Comment by SyscoreV1** [comment]
First, script is easier for editing, debugging and using with non-sudo user. 
Second, lol its not even 5% of my script. The real script have all that above plus api and external control panel, with crash detection and planned updates.

**Comment by yellows111** [comment]
you can have services run as service users too (with fine permissions that are going to be REQUIRED to be set in a future release)...

what is your point here?

**Comment by SyscoreV1** [comment]
With docker its better than your "cgroups-based containment", and its optimized to match 96% native performance. Even if someone did manage to X the server.

**Comment by SyscoreV1** [comment]
> you can have services run as service users too (with fine permissions that are going to be REQUIRED to be set in a future release)...
> 
> what is your point here?

My point is just a suggestion.

**Comment by modeco80** [comment]
> First, script is easier for editing, debugging and using with non-sudo user. Second, lol its not even 5% of my script. The real script have all that above plus api and external control panel, with crash detection and planned updates.

>First, script is easier for editing, debugging and using with non-sudo user.

Let's dissect this autism into easier to digest parts:

>easier for editing

Learn how to use a PC.

>debugging

Learn how to use a PC, or cat(1) (or journalctl if you're stuck on a busted ass bloated systemd computer).

>and using with non-sudo user.

OpenRC/systemd/whatever route you go, it's extremely easy to just specify a user.
If you can't do this, learn how to use a PC.


> With docker its better than your "cgroups-based containment", and its optimized to match 96% native performance. Even if someone did manage to X the server.

Docker literally uses cgroups2 lol, what is this point you're making
you're just using cgroups2 + a mount namespace/UTS namespace/network namespace lmao

By this logic, systemd/openrc simply using a cgroup should be faster than what retarded garbage you're doing.

>Second, lol its not even 5% of my script. The real script have all that above plus api and external control panel, with crash detection and planned updates.

>plus api and external control panel

Here's my API and control panel: `rc-service` or `systemctl`. External too, you can run them via SSH :^)

**Comment by SyscoreV1** [comment]
...

**Comment by dakrk** [comment]
> ...

dude's speechless
he just got proven wrong & OWNED

also why are you just putting random reactions on your posts are you that special

**Comment by SyscoreV1** [comment]
> > First, script is easier for editing, debugging and using with non-sudo user.
> 
> Let's dissect this autism into easier to digest parts:

Let's teach this "autism" how to use a brain.

> > easier for editing
> Learn how to use a PC.
> > debugging
> 
> Learn how to use a PC, or cat(1) (or journalctl if you're stuck on a busted ass bloated systemd computer).

Learn how to use your brain.


> > and using with non-sudo user.
> OpenRC/systemd/whatever route you go, it's extremely easy to just specify a user. If you can't do this, learn how to use a PC.

It has various reasons, its unnessary comparing to ./start, it also starts various services and fully restart all with one simple command. Of course I have custom permissions management.

> > With docker its better than your "cgroups-based containment", and its optimized to match 96% native performance. Even if someone did manage to X the server.
> 
> Docker literally uses cgroups2 lol, what is this point you're making you're just using cgroups2 + a mount namespace/UTS namespace/network namespace lmao

Docker can be used to route traffic across multiple servers with kubernetes and more advanced managing system the control panel isn't just a simple panel it also includes number of wss connected each session and ddos logs, and monitoring... docket is easier to deploy across servers, like you dont need to even setup routing. 

> By this logic, systemd/openrc simply using a cgroup should be faster than what retarded garbage you're doing.

Its faster but docker is safer if someone have access to admin. Besides cvm is know for its security bugs... docker is not cgroup, use your voided brains.

> > Second, lol its not even 5% of my script. The real script have all that above plus api and external control panel, with crash detection and planned updates.
> 
> > plus api and external control panel
> 
> Here's my API and control panel: `rc-service` or `systemctl`. External too, you can run them via SSH :^)

Web control panel, where i can restart or javascript console if something goes wrong and its all integrated with kubernetes.

Alright.

**Comment by DESKTOPGOOOSE** [comment]
this started out as a simple bug report and now it's turned into a full on shitshow lol

**Comment by dakrk** [comment]
> Let's teach this "autism" how to use a brain.

let's teach this idiot how to speak english properly

> docker is not cgroup, use your voided brains.

do you even know what cgroups are you smoothbrain

i can't be bothered reading the rest but holy shit dude you are such an annoying little idiot

**Comment by SyscoreV1** [comment]
> > Let's teach this "autism" how to use a brain.
> 
> let's teach this idiot how to speak english properly

Let us teach you how to respect others.

> > docker is not cgroup, use your voided brains.
> 
> do you even know what cgroups are you smoothbrain

Do you even know what docker is you smoothbrain

> i can't be bothered reading the rest but holy shit dude you are such an annoying little idiot

Holy * who started this war. Ask your self.

**Comment by DESKTOPGOOOSE** [comment]
can we knock it off we basically just started a shitshow

**Comment by SyscoreV1** [comment]
No, the conflict has been started.

**Comment by DESKTOPGOOOSE** [comment]
so what if i just

**Comment by DESKTOPGOOOSE** [comment]
actually that probably didnt work because im smoothbrained am i

**Comment by ghost** [comment]
@modeco80 @dartzcn lock this

**Comment by mvoolt** [comment]
***not going to quote the whole msg***

> Learn how to use your brain.

That's your excuse to using software that simplifies workarounds?

> It has various reasons, its unnessary comparing to ./start, it also starts various services and fully restart all with one simple command. Of course I have custom permissions management.

... I... Wow. How come it is unnecessary? Do you seriously value milliseconds typing less letters? Have you heard of aliases before? every shell has them, even cmd.exe/command.com. 

> Docker can be used to route traffic across multiple servers with kubernetes and more advanced managing system the control panel isn't just a simple panel it also includes number of wss connected each session and ddos logs, and monitoring...
docket is easier to deploy across servers, like you dont need to even setup routing.

Uhhh yeah many dedicated server providers already have DDoS monitors expect for what goes in the TCP/UDP traffic.

>Its faster but docker is safer if someone have access to admin. Besides cvm is know for its security bugs... docker is not cgroup, use your voided brains.

Yeah sure some people prefer Docker over the built-in `nobody` container/area/whatever in *NIX but the last sentence?... It does?????????????????????????? Well at least for resource limiting.

> Web control panel, where i can restart or javascript console if something goes wrong and its all integrated with kubernetes.

Yeah uhhhh JavaScript console? Is there any benefits in that???? Considering collab-vm-server is written in C++ not JS.


I am not going to reply to your next replies.

**Comment by SyscoreV1** [comment]
> _**not going to quote the whole msg**_
> 
> > Learn how to use your brain.
> 
> That's your excuse to using software that simplifies workarounds?

...

> > It has various reasons, its unnessary comparing to ./start, it also starts various services and fully restart all with one simple command. Of course I have custom permissions management.
> 
> ... I... Wow. How come it is unnecessary? Do you seriously value milliseconds typing less letters? Have you heard of aliases before? every shell has them, even cmd.exe/command.com.

Because I have loads of work to do and its near end of school tests are coming. i just can't simply. You'll still need scripts.

> 
> > Docker can be used to route traffic across multiple servers with kubernetes and more advanced managing system the control panel isn't just a simple panel it also includes number of wss connected each session and ddos logs, and monitoring...
> 
> docket is easier to deploy across servers, like you dont need to even setup routing. Uhhh yeah many dedicated server providers already have DDoS monitors expect for what goes in the TCP/UDP traffic.

I expect you to do some decent research before replying


> > Its faster but docker is safer if someone have access to admin. Besides cvm is know for its security bugs... docker is not cgroup, use your voided brains.
> 
> Yeah sure some people prefer Docker over the built-in `nobody` container/area/whatever in *NIX but the last sentence?... It does?????????????????????????? Well at least for resource limiting.

...

> > Web control panel, where i can restart or javascript console if something goes wrong and its all integrated with kubernetes.
> 
> Yeah uhhhh JavaScript console? Is there any benefits in that???? Considering collab-vm-server is written in C++ not JS.

Js console is for remote monitoring when in at school, how does that relate to c++.

> I am not going to reply to your next replies.

whatever.

**Comment by yellows111** [comment]
> ... You'll still need scripts.

At least with a service I don't have to look twice to see if its running every startup if I wanted it to.
Sure, I could use "scripts", but by that point i'd already be in the same directory as I would of wanted to be anyway if I wanted to directly launch, say, GDB.

> Js console is for remote monitoring when in at school, how does that relate to c++.

Have you considered... say, once... ssh(1)? I don't get hogging around a giant JS console just for managing something remotely, seeing as SSH is just more convenient once you set it up correctly.

<hr>

By the side, your continued questionable activity that really looks like you are trying to bait us for extreme reactions.

I don't see how you prolonging this is helpful to anyone, considering it's wasting my time, and I could be building the source of the program that is named after this repo many times over, helping others.

_I yet to have see what you are trying to achieve here._

**Comment by SyscoreV1** [comment]
> > ... You'll still need scripts.
> 
> At least with a service I don't have to look twice to see if its running every startup if I wanted it to. Sure, I could use "scripts", but by that point i'd already be in the same directory as I would of wanted to be anyway if I wanted to directly launch, say, GDB.

Scripts are the same as services if properly configured.

> > Js console is for remote monitoring when in at school, how does that relate to c++.
> 
> Have you considered... say, once... ssh(1)? I don't get hogging around a giant JS console just for managing something remotely, seeing as SSH is just more convenient once you set it up correctly.

my school blocks literally everything all i can do is use a webpanel.

> By the side, your continued questionable activity that really looks like you are trying to bait us for extreme reactions.


> I don't see how you prolonging this is helpful to anyone, considering it's wasting my time, and I could be building the source of the program that is named after this repo many times over, helping others.
> 
> _I yet to have see what you are trying to achieve here._

Idk

**Comment by modeco80** [comment]
i have a life people, stop bickering over a comment I made because I was tired of your shit
