### ISSUE TITLE
VM shows in UserVM, but image not shows

### ISSUE THREAD

**Issue by hugryy** [computernewb/collab-vm-server#123]
After starting CVM Server i see a message from browser: site 188.**.**.*** not sent data. I tried to install nginx and copy http folder to html folder and set permissions, but it show 403 error

**Comment by hugryy** [comment]
Who can help with that?

**Comment by mvoolt** [comment]
Open admin.min.js or whatever it is named then search for `serverAddress` then replace the value with a string (**INCLUDE QUOTATION MARKS, IT IS IMPORTANT**) or `prompt("server address","localhost:6004")`

**Comment by hugryy** [comment]
nothing changed(
![image](https://user-images.githubusercontent.com/76772320/157089278-d3604d01-d342-4200-a0b7-b4f8149f7c9a.png)

**Comment by mvoolt** [comment]
That's because it is trying to connect to localhost and not the server where your collab-vm-server instance is hosted on.

And I didn't mean to replace the prompt.

**Comment by hugryy** [comment]
I don't understand what should I do?

**Comment by mvoolt** [comment]
If you haven't typed in something in the prompt and let in the default string or prompt, it tries to connect to localhost:6005 and not the server.

**Comment by hugryy** [comment]
This normal?
![image](https://user-images.githubusercontent.com/76772320/157094989-3f3e0804-a5e9-4c01-bf13-1d531f994e36.png)

**Comment by mvoolt** [comment]
Yes. Just click OK after going in to admin panel.

**Comment by hugryy** [comment]
Nothing changed(, i think this my problem 
![image](https://user-images.githubusercontent.com/76772320/157095622-14375c26-3e0f-4b77-83fb-58051bda0e26.png)

**Comment by hugryy** [comment]
i used: chown www-data -R /usr/share/nginx/html

**Comment by hugryy** [comment]
This ok?

**Comment by mvoolt** [comment]
Guess so.

**Comment by hugryy** [comment]
Why web server deleted from cvm server?

**Comment by mvoolt** [comment]
Because the previous web server was a mess and pretty much a giant hack and CVM-server maintainers had to remove it.

**Comment by hugryy** [comment]
It's sad, but I will wait for help

**Comment by hugryy** [comment]
I FIXED THAT, 403 Forbidden has gone

**Comment by hugryy** [comment]
mvoolt, thanks for your help!!

**Comment by hugryy** [comment]
bruh, image from vm not shows
![image](https://user-images.githubusercontent.com/76772320/157102945-9aae98db-0e24-4f4f-89b5-6aa7273bacc2.png)

**Comment by hugryy** [comment]
![image](https://user-images.githubusercontent.com/76772320/157105663-9d194e35-282c-444e-93da-22349293b678.png)

**Comment by mvoolt** [comment]
mind if you share QEMU command? it might be a faulty one

**Comment by hugryy** [comment]
qemu-system-x86_64 -hda ubuntu.qcow -device e1000,netdev=net0,mac='DE:AD:BE:EF:87:1D' -netdev tap,id=net0,script=/etc/qemu-ifup -m 2048 -enable-kvm -cpu host -device usb-tablet -usb

**Comment by hugryy** [comment]
mvoolt, you here?

**Comment by SyscoreV1** [comment]
It's fine for the rest of us, if the binary is orignal and base system. Check your vm installation. 

Where are your vga and null monitor in qemucmd?

**Comment by SyscoreV1** [comment]
also your image name is Linux but uhh it's windows 8.1?

**Comment by hugryy** [comment]
yes

**Comment by hugryy** [comment]
What is null monitor and how to add it

**Comment by mvoolt** [comment]
You don't need to add `-monitor null` considering cvm-server already adds QMP arguments.

**Comment by hugryy** [comment]
Hmm, so what to do?

**Comment by hugryy** [comment]
This is strange, I opened UserVM a year ago and there were no such problems
