### ISSUE TITLE
Root value is not an object

### ISSUE THREAD

**Issue by hdfsyu** [computernewb/collab-vm-server#126]
I'm stupid at making QEMU VMs, but whenever I try to make a VM on the admin panel it says Root value is not an object, any help?

**Comment by dakrk** [comment]
(This is a 1.2 issue, you should've posted this on https://github.com/computernewb/collab-vm-server-1.2)

Does your QEMU command have double quotes in them? If so, you'll have to manually escape them with a backslash each time you edit the command. Annoying, but that's how it is.

**Comment by dakrk** [comment]
Nevermind I forgot this repo used to be the old 1.2 repo and the new one is archived oops

**Comment by hdfsyu** [comment]
> (This is a 1.2 issue, you should've posted this on https://github.com/computernewb/collab-vm-server-1.2)
> 
> Does your QEMU command have double quotes in them? If so, you'll have to manually escape them with a backslash each time you edit the command. Annoying, but that's how it is.

Oh, thanks for the info

**Comment by hdfsyu** [comment]
So like
\"quotes"\

**Comment by dakrk** [comment]
> So like "quotes"\

It'd be like `\"quoted text\"`

**Comment by hdfsyu** [comment]
ah thanks

**Comment by hdfsyu** [comment]
> > So like "quotes"\
> 
> It'd be like `\"quoted text\"`

Same thing...
Command I'm using is
`qemu-system-x86_64 -boot d -cdrom \"E:\Windows 98 Second Edition.iso\" -cpu n270-v1 -device sb16 -device cirrus-vga -usbdevice tablet -netdev user,id=n0 -device rtl8139,netdev=n0 -M pc-i440fx-2.5 -hda \"E:\windows xp vm\hdd.img\" -m 1G -qmp tcp:localhost:4444,server,wait=off -vnc :5900`

**Comment by yellows111** [comment]
try `qemu-system-x86_64 -boot d -cdrom \\\"E:\\Windows 98 Second Edition.iso\\\" -cpu n270-v1 -device sb16 -device cirrus-vga -usbdevice tablet -netdev user,id=n0 -device rtl8139,netdev=n0 -M pc-i440fx-2.5 -hda \\\"E:\\windows xp vm\hdd.img\\\" -m 1G`

**Comment by hdfsyu** [comment]
> try `qemu-system-x86_64 -boot d -cdrom \\\"E:\\Windows 98 Second Edition.iso\\\" -cpu n270-v1 -device sb16 -device cirrus-vga -usbdevice tablet -netdev user,id=n0 -device rtl8139,netdev=n0 -M pc-i440fx-2.5 -hda \\\"E:\\windows xp vm\hdd.img\\\" -m 1G`

Same error...

**Comment by yellows111** [comment]
i forgot the rest of the backslashes
`qemu-system-x86_64 -boot d -cdrom \\\"E:\\Windows 98 Second Edition.iso\\\" -cpu n270-v1 -device sb16 -device cirrus-vga -usbdevice tablet -netdev user,id=n0 -device rtl8139,netdev=n0 -M pc-i440fx-2.5 -hda \\\"E:\\windows xp vm\\hdd.img\\\" -m 1G`

or `qemu-system-x86_64 -boot d -cdrom \"E:\\Windows 98 Second Edition.iso\" -cpu n270-v1 -device sb16 -device cirrus-vga -usbdevice tablet -netdev user,id=n0 -device rtl8139,netdev=n0 -M pc-i440fx-2.5 -hda \\\"E:\\windows xp vm\\hdd.img\\\" -m 1G` if it doesn't boot

**Comment by hdfsyu** [comment]
> i forgot the rest of the backslashes `qemu-system-x86_64 -boot d -cdrom \\\"E:\\Windows 98 Second Edition.iso\\\" -cpu n270-v1 -device sb16 -device cirrus-vga -usbdevice tablet -netdev user,id=n0 -device rtl8139,netdev=n0 -M pc-i440fx-2.5 -hda \\\"E:\\windows xp vm\\hdd.img\\\" -m 1G`
> 
> or `qemu-system-x86_64 -boot d -cdrom \"E:\\Windows 98 Second Edition.iso\" -cpu n270-v1 -device sb16 -device cirrus-vga -usbdevice tablet -netdev user,id=n0 -device rtl8139,netdev=n0 -M pc-i440fx-2.5 -hda \\\"E:\\windows xp vm\\hdd.img\\\" -m 1G` if it doesn't boot

tysm! it worked

**Comment by hdfsyu** [comment]
> i forgot the rest of the backslashes `qemu-system-x86_64 -boot d -cdrom \\\"E:\\Windows 98 Second Edition.iso\\\" -cpu n270-v1 -device sb16 -device cirrus-vga -usbdevice tablet -netdev user,id=n0 -device rtl8139,netdev=n0 -M pc-i440fx-2.5 -hda \\\"E:\\windows xp vm\\hdd.img\\\" -m 1G`
> 
> or `qemu-system-x86_64 -boot d -cdrom \"E:\\Windows 98 Second Edition.iso\" -cpu n270-v1 -device sb16 -device cirrus-vga -usbdevice tablet -netdev user,id=n0 -device rtl8139,netdev=n0 -M pc-i440fx-2.5 -hda \\\"E:\\windows xp vm\\hdd.img\\\" -m 1G` if it doesn't boot

Never mind, it doesn't work. The root value is not an object error is gone, however it cannot connect to the VNC server. but it can connect to the QMP server...

**Comment by hdfsyu** [comment]
I also tried the other command that you sent and it still doesn't work

**Comment by yellows111** [comment]
is qemu already running, or another thing using that port, collab-vm-server (1.2) automatically adds VNC and QMP arguments that are specified, so adding them will make the VM not work.

**Comment by hdfsyu** [comment]
qemu is already running

**Comment by hdfsyu** [comment]
and there is nothing else which is using the port that i specified

**Comment by yellows111** [comment]
Then there would be a conflict if you say so. The VM must be launched by collab-vm-server to work as intended, with no interference. Make sure no extraneous QEMU processes are running, then try again.

**Comment by hdfsyu** [comment]
> Then there would be a conflict if you say so. The VM must be launched by collab-vm-server to work as intended, with no interference. Make sure no extraneous QEMU processes are running, then try again.

Alright, it says the VM has been started
tysm

**Comment by hdfsyu** [comment]
probably the most stupidest question i have asked so far, where can i find my VM @yellows111

**Comment by hdfsyu** [comment]
anyone?

**Comment by mvoolt** [comment]
did you setup the (standard) web app yet?

**Comment by hdfsyu** [comment]
no...
