### ISSUE TITLE
Where are the ODB headers for compiling on Windows?

### ISSUE THREAD

**Issue by swordlink1** [computernewb/collab-vm-server#127]
I tried to compile collab-vm-server 1.2.11 (with odb in path) with MSYS2 mingw64 and failed. I then asked mv_ about this, sent him my logs [here](https://files.catbox.moe/yc30a4.txt), and then mv_ said that I don't have the ODB headers or something similiar. He doesn't know where it is though. Can anyone tell me where it is? Thank you!

**Comment by dakrk** [comment]
are you sure you're using 1.2.11 since that version removed ODB and 
doesn't use it at all

**Comment by yellows111** [comment]
did you download from the releases page?
please re-clone from source.

**Comment by swordlink1** [comment]
Okay, I'll use the release-1.2.11 source instead of the releases page.
@dakrk I'll try with source cloning instead.

**Comment by swordlink1** [comment]
Also, just to add more info, this isn't a newly-installed MSYS2 mingw64.

**Comment by swordlink1** [comment]
Compiling it right now. I had to use `pacman -Sy --noconf mingw-w64-x86_64-toolchain git` instead of `pacman -S --noconf mingw-w64-x86_64-toolchain git` to fix `error: failed to prepare transaction (could not find database)`. The difference between the 2 commands is that one of them uses -Sy, while the other just uses -S (which was in the building.md).

**Comment by swordlink1** [comment]
Okay, I'm back. Will use the grab_deps.sh now.

**Comment by dakrk** [comment]
The scripts haven't been updated for ages and are outdated

**Comment by swordlink1** [comment]
Oh okay. Anyways, I'm doing this without odb in path. Also, I grabbed the dependencies for W64 then abandoned the mingw64 terminal for a long time. Logs are here: [Logs](https://files.catbox.moe/ghuddp.txt)

**Comment by dakrk** [comment]
as I said these scripts are outdated and you should just install the dependencies manually, excluding ODB
you do NOT need ODB, don't even touch it at all

**Comment by swordlink1** [comment]
Can you give the instructions on installing them manually?

**Comment by yellows111** [comment]
clang64
```
pacman -Syu
pacman -S mingw-w64-clang-x86_64-libvncserver mingw-w64-clang-x86_64-cairo mingw-w64-clang-x86_64-dlfcn mingw-w64-clang-x86_64-boost mingw-w64-clang-x86_64-sqlite3 mingw-w64-clang-x86_64-winpthreads-git git mingw-w64-clang-x86_64-make mingw-w64-clang-x86_64-clang
git clone https://github.com/yellows111/collab-vm-server.git --recursive
mingw32-make JPEG=1 -j$(nproc)
```
should work

**Comment by yellows111** [comment]
for library conflicts, im coping this old collab-vm-server win64 guide:
### To fix some compile errors, change a part of */include/psdk_inc/_socket_types.h:
from `typedef UINT_PTR	SOCKET;`
to `typedef unsigned __int64	SOCKET;` // may be not int64 on 32-bit needs to be investigated

### and a part of */include/boost/asio/detail/hash_map.hpp:
comment or remove out the entirety of `inline std::size_t calculate_hash_value(SOCKET s)`
it's under the rest of the `calculate_hash_value`'s

**Comment by swordlink1** [comment]
Sorry for not responding in a long time. Anyways, I'll do it now.

**Comment by swordlink1** [comment]
ERROR. [Logs](https://files.catbox.moe/4sagyr.txt)

**Comment by yellows111** [comment]
```diff
diff -ur $1 $2 > hash_map.diff -p4 
change the include path to your current prefix
--- "/include/boost/asio/detail/hash_map.hpp"
+++ "/include/boost/asio/detail/hash_map.hpp"
@@ -41,15 +41,15 @@ inline std::size_t calculate_hash_value(
   return reinterpret_cast<std::size_t>(p)
     + (reinterpret_cast<std::size_t>(p) >> 3);
 }
 
-#if defined(BOOST_ASIO_WINDOWS) || defined(__CYGWIN__)
+/* #if defined(BOOST_ASIO_WINDOWS) || defined(__CYGWIN__)
 inline std::size_t calculate_hash_value(SOCKET s)
 {
   return static_cast<std::size_t>(s);
 }
 #endif // defined(BOOST_ASIO_WINDOWS) || defined(__CYGWIN__)
-
+ */
 // Note: assumes K and V are POD types.
 template <typename K, typename V>
 class hash_map
   : private noncopyable
```
Worked for me
<hr>
Disclaimer: The above code is from the boost asio source code, file boost/asio/detail/hash_map.hpp .

**Comment by swordlink1** [comment]
THANK YOU SO MUCH!!! IT WORKS!!!
My canny level: [Godly Canny](https://youtu.be/q7h61EcVoyY?t=39)

**Comment by Undefishin** [comment]
> My canny level

You should be ashamed of yourself, Logan.

**Comment by enderman0125** [comment]
> THANK YOU SO MUCH!!! IT WORKS!!! My canny level: [Godly Canny](https://youtu.be/q7h61EcVoyY?t=39)

:frowning3:

**Comment by ghost** [comment]
> THANK YOU SO MUCH!!! IT WORKS!!! My canny level: [Godly Canny](https://youtu.be/q7h61EcVoyY?t=39)

[This is why I vandalized your page months ago.](https://www.youtube.com/watch?v=AAUh7DSNswc)

**Comment by swordlink1** [comment]
Calm down, it's a just a group of pixels in a certain arrangement being displayed on your screen. But, I tried to compile the collab-vm-admin-web-app-1.2 and I can't set the message of the day. Where is the option?

**Comment by dakrk** [comment]
> Calm down, it's a just a group of pixels in a certain arrangement being displayed on your screen.

and an unfunny arrangement of pixels at that

**Comment by Undefishin** [comment]
> Calm down, it's a just a group of pixels in a certain arrangement being displayed on your screen.
> and an unfunny arrangement of pixels at that

SO TRUE

**Comment by swordlink1** [comment]
It wasn't meant to be funny, it was just meant to express my feelings. Apparently I can't lower my expectations for the internet and still keep them high up for some god damn reason, just like how I can't find the option to change the message of the day.

**Comment by swordlink1** [comment]
So if everyone's done being a snowflake, does anybody know where to set the message of the day? Thank you.

**Comment by yellows111** [comment]
[@yellows111/collab-vm-admin-web-app](/yellows111/collab-vm-admin-web-app)

computernewb webapp repos outdated

**Comment by dakrk** [comment]
> So if everyone's done being a snowflake

lmao

> just like how I can't find the option to change the message of the day

use the repo yellows sent, but checkout from b31aa4acd5e81cb173eb06ca7cd4654a7cb5d6c0 as I believe the newer commits are for features that aren't relevant in the main server repo

**Comment by ghost** [comment]
> So if everyone's done being a snowflake

The problem is not us being offended by it, it's the fact that the "becomes (un)canny" meme is painfully unfunny.

**Comment by swordlink1** [comment]
> lmao

Typical CollabVM user. But again, what do I expect, or rather, _why_ do I expect?

> it's the fact that the "becomes (un)canny" meme is painfully unfunny.

You do you. But I do agree, although it's _not_ painfully unfunny, just not designed to be funny (everyone thinks the creator of the meme intention was to make the meme funny, although it wasn't) It's probably not a meme, just a trend.

> use the repo yellows sent, but checkout from b31aa4acd5e81cb173eb06ca7cd4654a7cb5d6c0 as I believe the newer commits are for features that aren't relevant in the main server repo

Eh, it's already too late and I used the latest commit by git cloning the repository git file, and I don't think I see any features that out of place.

**Comment by swordlink1** [comment]
@yellows111 How can I get a account on your Windows Server 2019 RDP?

**Comment by Undefishin** [comment]
you cant lol

**Comment by swordlink1** [comment]
Why?

**Comment by Undefishin** [comment]
Also why are you going out of topic for no reason?

**Comment by swordlink1** [comment]
Because I want to know how to get a account.

Edit: We went out of topic before with the canny thing.

**Comment by dakrk** [comment]
how you even know about it in the first place is a bit odd

such a person as you wouldn't get access to it anyway

**Comment by dakrk** [comment]
the thing you originally made the issue for has been solved so let me just:

**Comment by modeco80** [comment]
here this will fix the problem
