### ISSUE TITLE
Can't create a VM

### ISSUE THREAD

**Issue by Rix565** [computernewb/collab-vm-server#131]
If I try to create a VM, the admin panel will show "Loading..." indefinitely and looking at the websocket logs, the server rdoesn't seems to care about the VM creation request.

If I try to reload the page, no VM has been created.

Help!

**Comment by Rix565** [comment]
UPDATE: once I create a VM manually by editing the DB, the admin panel, once logged in, stucks in a "Loading..." loop.

**Comment by dakrk** [comment]
What appears in the JS console of the admin panel once it gets stuck?

**Comment by Rix565** [comment]
Nothing. Just a little favicon.ico error.

**Comment by dakrk** [comment]
Huh, so not an admin panel issue then.
What appears in the network tab in the devtools for the server WebSocket? Does it send anything before getting stuck, or does it outright close the connection?

**Comment by Rix565** [comment]
3.nop indefinitely, on both sides (client & server)

**Comment by elijahr2411** [comment]
Can you send your collab-vm-server logs? Just copy-pasting the terminal output into a code block should be fine

**Comment by elijahr2411** [comment]
Also, couple questions: Are you using the admin panel bundled with this repository? And are you running collabvm directly through a terminal, using a daemon system like systemd, or something else

**Comment by yellows111** [comment]
OK, now i'm confused. The only time i've seen infinite loading is during these two situations:
1: The server has crashed.
2: The Admin Web App's JS has stopped executing

From what i've reading, it's not 1 as reconnecting is fine, 2 is more likely here, but without a trace, i'm conflicted on what that would be.

Despite it being out of place for the server repo, I'm going to pretend this is an AWA issue originally here and ask:

What browser do you use?
Any experimental features enabled?
Does making a new profile fix this issue?

**Comment by Rix565** [comment]
```
CollabVM Server Started
QEMU Command: qemu-system-x86_64 -hda /home/rixy/fuckvm/img/vm1.qcow2 -cdrom /home/rixy/Téléchargements/en_windows_xp_professional_x64.iso -enable-kvm -cpu host -m 1024 -vga cirrus -net nic,model=rtl8139 -net user -usbdevice tablet
VM controller ID: xp is starting
QEMU process ID: 12671
Starting QEMU with command:
qemu-system-x86_64 -hda /home/rixy/fuckvm/img/vm1.qcow2 -cdrom /home/rixy/Téléchargements/en_windows_xp_professional_x64.iso -enable-kvm -cpu host -m 1024 -vga cirrus -net nic,model=rtl8139 -net user -usbdevice tablet -no-shutdown -qmp tcp:127.0.0.1:5200,server,nodelay -vnc 127.0.0.1:0 
qemu-system-x86_64: -qmp tcp:127.0.0.1:5200,server,nodelay: info: QEMU waiting for connection on: disconnected:tcp:127.0.0.1:5200,server=on
Trying 127.0.0.1:5200...
Connected to QEMU
Connected to QMP
[QEMU] Setting task 12671 nice level to 19
26/10/2022 19:42:15 VNC server supports protocol version 3.8 (viewer 3.8)
26/10/2022 19:42:15 We have 1 security types to read
26/10/2022 19:42:15 0) Received security type 1
26/10/2022 19:42:15 Selecting security type 1 (0/1 in the list)
26/10/2022 19:42:15 Selected Security Scheme 1
26/10/2022 19:42:15 No authentication needed
26/10/2022 19:42:15 VNC authentication succeeded
26/10/2022 19:42:15 Desktop name "QEMU"
26/10/2022 19:42:15 Connected to VNC server, using protocol version 3.8
26/10/2022 19:42:15 VNC server default format:
26/10/2022 19:42:15   32 bits per pixel.
26/10/2022 19:42:15   Least significant byte first in each pixel.
26/10/2022 19:42:15   TRUE colour: max red 255 green 255 blue 255, shift red 16 green 8 blue 0
VM controller ID: xp has been started
[WebSocket Connect] IP: 127.0.0.1
[Username Assigned] IP: 127.0.0.1 New username: "guest93412"
26/10/2022 19:42:58 Got new framebuffer size: 720x396
[WebSocket Connect] IP: 127.0.0.1
```
It show that I'm connected to the admin panel, and.... nothing. Just a endless Loading screen.

And I'm using the admin panel bundled with this repo, using terminal to execute the server (in sudo tho), and I'm using Firefox, with no experimental features. Didn't check on a new profile, will do that later.

**Comment by elijahr2411** [comment]
Does that log include when you tried to create the vm? If so looks like the server might not even be getting the creation message which is odd

**Comment by Rix565** [comment]
Nope, because I created a VM manually by editing the .db file, and now the admin panel is endless with a Loading... screen once I type the master password (btw not encrypted, but you guys should)

**Comment by elijahr2411** [comment]
yeah we know, implementing anything new into this software is pretty much a no-go at this point unfortunately. Anyways, can you try compiling [https://github.com/yellows111/collab-vm-admin-web-app](https://github.com/yellows111/collab-vm-admin-web-app) and creating the vm through there?

**Comment by yellows111** [comment]
First off, please avoid using sudo to launch collab-vm-server. Best situation for that is using an unprivileged user with the kvm group if required.

Second off, I think the fact you use accented characters (such as: á, é,  í, ó and ú) in your parameters is making AWA throw up.
Technically, this is a bug in the AWA, but it's better to avoid the problem all together by using strictly non-accented valid path ASCII characters (0-9, A-Z, a-z, _, -) in your parameters (Name, path, and such input boxes).

I think that's what's happening here.

**Comment by Rix565** [comment]
OK, but I'll do that later. For now, with my manually added VM, it works perfectly fine (on the non-admin webapp).

**Comment by Rix565** [comment]
i can't edit this lol, i'm installing windows xp currently

i can edit this later

**Comment by Rix565** [comment]
PS: anything else (except the admin panel, obviously) works perfectly fine.

i can take a turn, keyboard is recorded, the virtual mouse follows your mouse movements; etc, etc etc...

**Comment by Rix565** [comment]
It works!!!

For other people having the same problem:
à, é, ç, and other characters should not be used AT ALL!
