### ISSUE TITLE
collab-vm-server.exe - Application Error

### ISSUE THREAD

**Issue by archcloudy** [computernewb/collab-vm-server#134]
The exception Illegal Instruction
An attempt was made to execute an illegal instruction.
 (0xc000001d) occurred in the application at location 0x00007FF622715CF9

Click on OK to terminate the program

Honestly this never happened when i was on Windows 10 22H2
but when i'm on Windows 11, i couldn't run the server now.

CollabVM 1.2.11 SE SP1
Windows 11 22H2 10.0.22621.2134
![image](https://github.com/computernewb/collab3/assets/86261006/bea43892-e8c4-423c-8397-d0c3d3261976)

**Comment by ghost** [comment]
I recommend trying the newer, 1.2.ts version of the server. https://github.com/computernewb/collabvm-1.2.ts, which I can confirm works perfectly on Windows 11.

**Comment by archcloudy** [comment]
i did tried but j can't seem to figure out how to create multiple vms

> I recommend trying the newer, 1.2.ts version of the server. https://github.com/computernewb/collabvm-1.2.ts, which I can confirm works perfectly on Windows 11.
