### ISSUE TITLE
i cant get the collab vm server 2.0 to work

### ISSUE THREAD

**Issue by coo-github** [computernewb/collab-vm-server#42]
every time it keeps saying this app isnt compatible with your pc so i dont know what is going on

**Comment by Mayank-1234-cmd** [comment]
i think its meant for linux not windows

**Comment by SplitXPlayZ** [comment]
Maybe the server or the application on your PC isn't compatible. I recommend using the application on a Linux environment.

**Comment by bedriczwaleta** [comment]
reaganvps is in windows and linux is by far not too popular
so coo and me are trying to compile

**Comment by SplitXPlayZ** [comment]
It works completely fine on my linux VPS.

**Comment by bedriczwaleta** [comment]
what is ur linux vps

**Comment by bedriczwaleta** [comment]
coo has no linux vps

**Comment by computernewb** [comment]
Is your OS 32-bit or ARM? CVM 2.0 does not support either. CVM 1.2 I know can build on ARM and 32-bit though.

**Comment by coo-github** [comment]
> Is your OS 32-bit or ARM? CVM 2.0 does not support either. CVM 1.2 I know can build on ARM and 32-bit though.

My OS is 64-bit on Windows 10 Home.

**Comment by Mayank-1234-cmd** [comment]
try making a linux virtual machine (virtualbox/vmware) then downgrade gcc (as yellows111 said)
```
sudo apt install gcc-7-base=7.3.0-16ubuntu3 cpp-7=7.3.0-16ubuntu3 gcc-7=7.3.0-16ubuntu3 libgcc-7-dev=7.3.0-16ubuntu3 libasan4=7.3.0-16ubuntu3 libubsan0=7.3.0-16ubuntu3 libcilkrts5=7.3.0-16ubuntu3  
sudo apt install g++-7=7.3.0-16ubuntu3 libstdc++-7-dev=7.3.0-16ubuntu3  
sudo ln -s /usr/bin/g++-7 /usr/bin/g++  
sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc  
sudo ln -s /usr/bin/gcc /usr/bin/cc
```
then if you follow the instructions in readme.md everything should work.

**Comment by Mayank-1234-cmd** [comment]
I hid that comment because readme.md has other instructions for windows.

**Comment by yellows111** [comment]
What the hell (this is like, the worst issue i've seen yet...)
What binary are you even trying to run?

**Comment by coo-github** [comment]
im not really having the issue anymore so theres no point on keeping this issue open for barely any reason
