### ISSUE TITLE
The collabvm servers are a huge pile of toxic waste

### ISSUE THREAD

**Issue by yg8ijvjvjv** [computernewb/collab-vm-server#48]
![](https://i.redd.it/thw4j1uwj9k61.png)

Also there are 24 forkies, I suggest disabling forks and shutting down the repository and the toxic servers

**Comment by modeco80** [comment]
The Github Issues are for *actual* issues with the collab-vm-server itself, ***NOT*** a forum for you to whine about someone stopping you from running MEMZ.


*Closed*.

**Comment by yg8ijvjvjv** [comment]
It's nothing to do with MEMZ. It is a serious issue to the collab-vm-servers because of pollution.
