### ISSUE TITLE
Fix cmake builds on Ubuntu/Debian

### ISSUE THREAD

**Issue by dartzcn** [computernewb/collab-vm-server#68]
Right now, it is very difficult to build the cmake version of CollabVM Server on Ubuntu and Debian because they lack the libjpeg-turbo-config.cmake file in the official repos. Arch Linux and CentOS doesn't have this problem, as far as I know.

**Comment by re9177** [comment]
able to reproduce under MSYS2 (both MinGW32 and MinGW64), packages have the identical problem

**Comment by yellows111** [comment]
Following on the MSYS2 comment, it seems the clangXX variant of MSYS2 has the libjpeg-turbo-config.cmake file.

**Comment by modeco80** [comment]
Not using the 1.3 cmake buildsystem anymore. I'll probably have to see how to solve this (although we probably won't need libjpeg-turbo?)
