### ISSUE TITLE
Fix Mac Builds

### ISSUE THREAD

**Issue by dartzcn** [computernewb/collab-vm-server#74]
1.2.10 and below can't be built on MacOS machines unless you remove the prctl.h header in QEMUController.cpp. Also, timestamp.cpp errors out on line 76 for some reason.

**Comment by yellows111** [comment]
Seems that gettimeofday doesn't exist properly on macOS?
Needs a triage to see if this is an library/implementation bug.

**Comment by modeco80** [comment]
I sort of tackled this in the latest dev/3.0.0 commit, maybe I'll backport that later.

Since guac is going byebye in 3.0 I'm gonna close this, maybe reopen it if 1.2.11 mac support is really worth exploring? (I doubt it)
