### ISSUE TITLE
Use Boost.Process library for all process handling

### ISSUE THREAD

**Issue by modeco80** [computernewb/collab-vm-server#75]
I have this typed up in a yakshaving document, but I'm gonna notate it here because.

Basically what the title says, move the code to a new class, make QEMUController use it, and OBLITERATE any uses of system() and replace them with this child process class (which will also have signals/events code can use to listen to important events... Or you can just fire it, the ~~honey badger~~ ChildProcess doesn't give a fuck).

The general current API for this new class (from my WIP tree):

```cpp
namespace util {

	// TODO (maybe):
	// - pipes for stdin/stdout/stderr (is this needed?)

	/**
	 * Class for managing a child process.
	 * It's what it says on the tin.
	 */
	struct ChildProcess : public std::enable_shared_from_this<ChildProcess> {
		#ifdef _WIN32
			using pid_type = pid_t;
		#else
			using pid_type = DWORD;
		#endif

	private: // Boost signals

		// TODO: a OnStart signal?

		/**
		 * Signal called when the process exits.
		 */
		boost::signals2::signal<void()> OnExit;

	public:
		// TODO(maybe?):
		// destructor which calls this->Kill(SIGTERM); ?

		using OnExitSlot = decltype(OnExit)::slot_type;

		boost::signals2::connection DoOnExit(const OnExitSlot& slot);

		/**
		 * Queries if this child process is running.
		 */
		bool Running() const;

		/**
		 * Attempt to start this child process.
		 *
		 */
		bool Start(const std::string& path, const std::vector<std::string>& args = {});

		/**
		 * Kill this child process
		 * if it's running.
		 *
		 */
		bool Kill(int sig = SIGTERM);

		/**
		 * Gets the PID of this child process.
		 * Valid only if this->Running() == true. Without asserts,
		 * will just return -1.
		 *
		 * \returns the PID of the child process.
		 */
		pid_type Pid() const;

		/**
		 * Get the exit code of the process.
		 * Valid only if this->Running() == false.
		 */
		int ExitCode() const;

	// TODO: Doesn't work on Windows
	// (and probably won't. Windows SUCKS with process hiearchies.)

		/**
		 * Get a promise that will be set when the child process dies.
		 * This can be used to, for instance, wait for a process to die before exiting.
		 */
		std::promise<void> GetPromise();
	};

} // namespace util
```

(I know boost.process exists, but the code mostly exists and sort of works, so I'd like to just make it work better.)

Lifetime/general concerns:

 - We currently use shared_from_this() which means everyone has to be a `shared_ptr<util::ChildProcess>`. Might be limiting.
 - We abuse the ASIO signal set we use to listen for process signals to increase lifetime until the process exits and the OnExit signal has been called.

**Comment by modeco80** [comment]
you know.. Boost.Process may actually be worth using, cause I've been trying to see how to handle child supervision on windows asynchronously and it's actually the worst most painful thing ever

Boost.Process also integrates with asio very well, meaning that the complex signal_set things QEMUController does to supervise QEMU?

```cpp
#include <cstdio>

#include <boost/asio.hpp>

#include <boost/process/args.hpp>
#include <boost/process/async.hpp>
#include <boost/process/child.hpp>
#include <boost/process/search_path.hpp>

namespace process = boost::process;

int main() {
	boost::asio::io_service service;

	process::child qemu(process::search_path("qemu-system-x86_64"), 
		process::args = {"-accel", "kvm"},

		process::on_exit = [](int exitCode, const std::error_code& ec) {
			std::printf("child process exited with code %d\n", exitCode);
		}, 
	service);

	
	service.run();

	return 0;
}
``` 

Literally expressed in 3 LOC (if not 1, since the lambda here is just test code, honestly.). To add, this code runs universally everywhere Boost.Process supports *out of the box*, not just POSIX. 

One minor gripe is that Boost.Process still uses boost::filesystem for `search_path`, although I may just be missing something. Would not be the first time that's happened.

EDIT: OK, no i wasn't missing anything, it explicitly uses Boost.Filesystem for that for some reason. WTH. Oh well, if it's really a problem we can just implement *that* using the standard library version

**Comment by yellows111** [comment]
This is great, but we are currently being blocked by boost on win32/win64 with handle_workaround.hpp, which I've mentioned on #76.

**Comment by modeco80** [comment]
That isn't entirely a boost issue, although 9d677f0 *should* fix it. Once I fix resetting being a bit wonky this issue can be closed.

I may also completely abstract away Boost.Process using an interface like:

```cpp
struct ChildProcess {
	// some function to set a internal on exit handler

	virtual int ExitCode() = 0;

	virtual void Kill() = 0;
};

// all of the existing child processes return a internal implementation,
// but are signatured as shared_ptr<ChildProcess> or something
```
Kind of iffy, especially since virtual functions are involved, but it's not like these functions would be called every 16 milliseconds or something. It'd also be a tiny bit of an improvement on compile time (although the cosmic tier header dependencies in collabvm.h will make this kinda moot for a while)

**Comment by yellows111** [comment]
Seems to not error out anymore. Fixed and compiled successfully on the fork that #76 is using.

**Comment by modeco80** [comment]
Doesn't matter anymore, Closing!
