### ISSUE TITLE
collab-vm-server.exe has stopped working

### ISSUE THREAD

**Issue by Vichingo455** [computernewb/collab-vm-server#77]
The program crash when I run it
Screenshot:
![image](https://user-images.githubusercontent.com/59311016/137596351-c5be266c-f0ab-4667-924c-d0c0d42cdeb9.png)
Windows version: Windows 10
Server version: SE SP1

**Comment by Vichingo455** [comment]
At the moment I don't have the computer where I have this issue, but when I can I will upload it. A little bit more:

1. It's a computer upgraded from Windows 8.1 to Windows 10
2. It doesn't have the latest updates (won't install them)

**Comment by modeco80** [comment]
Closing as nothing really happened.

**Comment by Vichingo455** [comment]
> Hey, could you please upload a collab-vm-server.exe.*.dmp file? that'd help me in trying to figure out the problen you are having.

I don't have any files with an .dmp extension

**Comment by Vichingo455** [comment]
@modeco80 Reopen the issue. I don't have any files with a dmp extension
