### ISSUE TITLE
Collabvm Server Multithreading

### ISSUE THREAD

**Issue by SyscoreV1** [computernewb/collab-vm-server#80]
Add multithreading support.

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
lol

**Comment by yellows111** [comment]
```cpp
// Uncomment this to allow Asio to use multi-threading. WARNING: Might be buggy
//#define ENABLE_ASIO_MULTITHREADING
```

\- /src/Main.cpp lines 8 and 9

Note: I have not tested if this actually works, it's been in the source for... A long time.

**Comment by modeco80** [comment]
It does, but for some reason makes cvm server use a lot more memory (like 800m over like 250m)

**Comment by modeco80** [comment]
Closing as even as a feature request this doesn't make sense (it's already in the code!). This may become a supported option at one point anyways.

**Comment by win20-official** [comment]
Usage: [Port] [HTTP dir]
Port - the port to listen on for websocket and http requests
HTTP dir (optional) - the directory to serve HTTP files from. defaults to "http" in the current directory
        Ex: 80 web
help me
