### ISSUE TITLE
We need CloudFlare we need whitelister

### ISSUE THREAD

**Issue by SyscoreV1** [computernewb/collab-vm-server#87]
We need cloudflare! We need cloudflare! We need cloudflare! We need cloudflare! We need cloudflare! We need cloudflare! We need cloudflare! We need cloudflare! We need cloudflare! We need cloudflare! We need cloudflare! We need cloudflare! We need cloudflare! We need cloudflare! We need cloudflare! We need cloudflare! We need cloudflare! We need cloudflare!

we need whitelister we need whitelister we need whitelister we need whitelister we need whitelister we need whitelister we need whitelister we need whitelister we need whitelister we need whitelister we need whitelister we need whitelister we need whitelister we need whitelister we need whitelister we need whitelister we need whitelister we need whitelister we need whitelister

**Comment by SyscoreV1** [comment]
Gimme cloudflare Gimme cloudflare Gimme cloudflare Gimme cloudflare Gimme cloudflare Gimme cloudflare Gimme cloudflare Gimme cloudflare Gimme cloudflare Gimme cloudflare Gimme cloudflare Gimme cloudflare Gimme cloudflare Gimme cloudflare

Gimme whitelister Gimme whitelister Gimme whitelister Gimme whitelister Gimme whitelister Gimme whitelister Gimme whitelister Gimme whitelister Gimme whitelister Gimme whitelister Gimme whitelister Gimme whitelister Gimme whitelister Gimme whitelister

**Comment by modeco80** [comment]
This is how we get banned from creating issues.
