### ISSUE TITLE
[1.3.0] macOS: XCode Build Tools does not support c++20 (Mojave)

### ISSUE THREAD

**Issue by yellows111** [computernewb/collab-vm-server#89]
trying to `make JPEG=1 DEBUG=` for test/1.3.0 results in `error: invalid value 'c++20' in 'std=c++20'.

It supports up to c++17 or c++2a.

LLVM version: 10.0.1 (clang-1001.0.46.4)
Vendor: apple
Target: x86_64-apple-darwin18.7.0 

Installed via: prompt from attemping to use developer tools, which installed XCode and the said developer command line tools.

**Comment by yellows111** [comment]
After using Homebrew, I got to the point of it not complaining about c++20 and to start building...

Only to fail with 'boost/program_options.hpp' not found...

So I checked, upstream isn't providing a program-options package... that's... not helpful.

**Comment by yellows111** [comment]
It seems to actually do, just it wasn't importing the library directories... bad sign in more than one place.

**Comment by yellows111** [comment]
After attempting to fix that, it seems to be ignoring standard libraries?

(Why is building for this so weird...)

**Comment by dartzcn** [comment]
Unfortunately it's up to Apple to add support for this. Building 1.2.11 should still work fine though.

A couple other things are also broken in MacOS, mainly the use of prctl.h in QEMUController.cpp and ``gettimeofday`` in timestamp.cpp, which appears to be a bug with Mac's implementation of the function.

**Comment by modeco80** [comment]
I'll guard prctl.h when i revert back to the old QEMUController process code (:cry:) with linux, and Guacamole will be going "Holy Guacamole" here in a bit anyways.

**Comment by modeco80** [comment]
Closing since rewrite:tm:
