### ISSUE TITLE
Server statics 

### ISSUE THREAD

**Issue by SyscoreV1** [computernewb/collab-vm-server#93]
Add some statics collector like total hours viewed total hours used.
How many resets, how many kick or bans. View vs click rate. Cpu usage, ram usage.

**Comment by modeco80** [comment]
literally near half of these are worthless

cpu usage/ram usage might be useful to have for monitorings sake although itd be more worthwhile feeding data to something like grafana or netdata (and netdata already takes care of cpu/ram/disk-io/net-io for us, although it might be nice to get unadulterated vm statistics)

**Comment by modeco80** [comment]
Don't feel like doing this, will probably do it if and when it is something we might want (If you want this now, I reccomend using netdata, since its cgroup monitoring is very good. But that implies you know how to setup CVM as a service. If you don't, you probably shouldn't be hosting CollabVM.)
