### ISSUE TITLE
Rare crash on server

### ISSUE THREAD

**Issue by qtAmyVT** [computernewb/collab-vm-server#98]
I got a rare crash error, is my installation is broken, or is it the code already itself?

Informations:
GitHub: `release/1.2.11`
OS: Fedora 34

```24/11/2021 22:14:42 read (104: Connection reset by peer)
Disconnected from VNC server
qemu-system-i386: -qmp unix:/tmp/collab-vm-qmp-sandbox-vm1,server: info: QEMU waiting for connection on: disconnected:unix:/tmp/collab-vm-qmp-sandbox-vm1,server
QMP read error: End of file
QMP failed to connect. Retrying...
qemu-system-i386: warning: Unknown firmware file in legacy mode: etc/msr_feature_control
Connected to QEMU
Connected to QMP
[QEMU] Setting task 2602798 nice level to 19
24/11/2021 22:14:44 VNC server supports protocol version 3.8 (viewer 3.8)
24/11/2021 22:14:44 We have 1 security types to read
24/11/2021 22:14:44 0) Received security type 1
24/11/2021 22:14:44 Selecting security type 1 (0/1 in the list)
24/11/2021 22:14:44 Selected Security Scheme 1
24/11/2021 22:14:44 No authentication needed
24/11/2021 22:14:44 VNC authentication succeeded
24/11/2021 22:14:44 Desktop name "QEMU (VM1)"
24/11/2021 22:14:44 Connected to VNC server, using protocol version 3.8
24/11/2021 22:14:44 VNC server default format:
24/11/2021 22:14:44   32 bits per pixel.
24/11/2021 22:14:44   Least significant byte first in each pixel.
24/11/2021 22:14:44   TRUE colour: max red 255 green 255 blue 255, shift red 16 green 8 blue 0
VM controller ID: sandbox-vm1 has been started
24/11/2021 22:14:45 Got new framebuffer size: 640x480
24/11/2021 22:14:50 Got new framebuffer size: 1024x768
[WebSocket Disconnect] IP: [no] Username: "guest17767"
collab-vm-server: ../nptl/pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
qemu-system-i386: terminating on signal 15 from pid 4047616 ()
Aborted (core dumped)
```

**Comment by dwarfpuzzles** [comment]
[relates that the lock failed to [mutex_data_owner ](https://stackoverflow.com/questions/1105745/pthread-mutex-assertion-error)in ur pc
](https://stackoverflow.com/questions/1105745/pthread-mutex-assertion-error)

**Comment by dwarfpuzzles** [comment]
https://stackoverflow.com/questions/1105745/pthread-mutex-assertion-error

**Comment by qtAmyVT** [comment]
Oopsies for the title, i wasn't really paying attention to the error itself. The bug is related to threading.

**Comment by modeco80** [comment]
i guess something is unlocking a mutex locked on another thread yay*

*every time I touch the code to this thing I wanna `rm -rf src/` and start fresh. Might not be that bad of an idea tbh.

**Comment by qtAmyVT** [comment]
> i guess something is unlocking a mutex locked on another thread yay*
> 
> *every time I touch the code to this thing I wanna `rm -rf src/` and start fresh. Might not be that bad of an idea tbh.

No idea if it is a good or bad thing to erase the code and rewrite it from the ground up

**Comment by modeco80** [comment]
well I mean this code basically just *is* code smells the way it is right now. Ive certainly helped but its not enough

also websocketmm was kind of how I got to understand beast so its code is really garbo

**Comment by modeco80** [comment]
congrats you get the "first issue to get this label in like 6 months" award (helpful advice: please mark your issue with these track labels, so I don't have to do it. Thanks in advance)

didn't see it was 1.2.x track at first lol which is why I made rewriting comments

**Comment by yellows111** [comment]
Fun Side-note: GitHub doesn't let none-Collaborators (NOT even OP/Author or Contributors) add labels to issues, which is why the 1.2.x label was not added to this issue beforehand.

Thanks GitHub!

**Comment by modeco80** [comment]
Not gonna bother working on this cause I have better to do lol

**Comment by qtAmyVT** [comment]
Closing this issue such i have a different problem with collab-vm-server at the time.
